from MyEventManagerTest import MyEventManagerTest
from TimeTest import TimeTestCase
from AttendeeTest import AttendeeTest
from OrganiserTest import OrganiserTestCase
from LocationTest import LocationTest
from ReminderTest import ReminderTestCase
from EventTest import EventTest

TimeTestCase
OrganiserTestCase
LocationTest
ReminderTestCase
AttendeeTest
EventTest
MyEventManagerTest